sudo: false
language: haskell
ghc:
  - "7.8"
  - "7.6"

script:
  - cabal configure --enable-tests && cabal build && cabal test && cabal check
  # - find . -name '*.hs' -not -path '*/\.*' | xargs ~/.cabal/bin/hlint
